# UGLY SWEATER CHECKER:
# LOGS YOUR UGLY SWEATER AND MAKE SURE YOU ARE NOT IN DANGER OF 
# SOMEONE ELSE WEARING THE SAME SWEATER TO THE UGLY SWEATER PARTY

# REQUIRE GEMS, SURPRISE OUTPUT ON THE SCREEN MATCHING THE COLOR OF YOUR SWEATER 

# NOTE: COLORS TABLE, PATTERNS TABLE, OBJECTS TABLE, PICTURES TABLE, SAYINGS TABLE 
# ALREADY CREATED IN DIRECTORY

# CREATE SQLITE DATABASE TO TAKE IN SWEATER DETAILS


# CREATE NAMES TABLE TO TAKE IN NAME AND THEIR UGLY SWEATER ATTRIBUTES

# ADD TEST INTERFACE TO ADD FIRST UGLY SWEATER

# ADD MORE SWEATERS

# ADD USER INTERFACE TO ADD EVEN MORE SWEATER

# RETURN THE SWEATER ATTRIBUTES TO THE CONSOLE USING THE SAME COLOR TEXT AS THE COLOR OF THEIR SWEATER

# COMPARE CURRENT ENTRY TO OTHER SWEATERS

# IF SWEATER IS THE SAME AS OTHER SWEATER THEN ALERT USER













