# UGLY SWEATER CHECKER
# LOGS YOUR UGLY SWEATER AND MAKE SURE YOU ARE NOT IN DANGER OF 
# SOMEONE ELSE WEARING THE SAME SWEATER TO THE UGLY SWEATER PARTY

# REQUIRE GEMS, SURPRISE OUTPUT ON THE SCREEN TO THE COLOR OF YOUR SWEATER 

# CREATE SQLITE DATABASE TO TAKE IN SWEATER DETAILS

# CREATE NAMES TABLE TO TAKE IN NAME AND SIZE OF PERSON'S LOGGING THEIR SWEATER

# CREATE COLORS TABLE

# CREATE 3D OBJECT TABLE

# CREATE PICTORIAL TABLE

# CREATE PATTERN TABLE

# CREATE TEXT TABLE 

# ADD TEST INTERFACE TO ADD FIRST UGLY SWEATER

# ADD USER INTERFACE TO ADD SWEATER

# RETURN TO THE USER IN COLOR THE SWEATER THEY JUST ENTERED

# COMPARE CURRENT ENTRY TO OTHER SWEATERS
# IF SWEATER IS THE SAME AS OTHER SWEATER THEN ALERT USER













